- conn.go
TSVWithNamesAndTypes alias has been added only in version: v1.1.54267-testing
This patch fixes compatibility with earlier versions.
> Use long format name instead of alias #3

- README.md
- conn_test.go
- types.go
- types_test.go
the golang database/sql does to allow to use big uint64 values.
this PR provides a new type UInt64, which allows to wrap such kind of values to use in the driver.
fixes issue #11
> add type UInt64 to avoid database/sql limitations

- encoder.go
- encoder_test.go
- types_test.go
- strings.Split with empty slice argument returns slice with 1 element
which is empty string. without check len decoder crashes on empty
numeric arrays
- encoder test added
- types test added
> [encoder] fix zero len array decoding

- config.go
- conn.go
- encoder.go
- encoder_test.go
- rows.go
- rows_test.go
Add support of zoned datetime and recalculation of zoned time returned from database as a config option.
> support zoned datetime format

- conn.go
- conn_test.go
- errors.go
This reverts commit 1d0076b2e74b0057628a7bb22a0113fb0cabfc05, reversing
changes made to 7cb83a2242fff54a3629866bdab9479eef95cd76.
В read-only запросах текст запроса передается через тело запроса, а не через урл.
> Revert "Merge pull request #22 from azaikin/query-url"

- conn.go
- conn_go18.go
- rows.go
- rows_test.go
An alternative approach to #37. Being not aware of that pull request I did something similar myself.
Here is a list of changes I introduce:
* instead of passing `[]byte` as a result of `*conn.doRequest` slice I simply pass the `resp.Body` which is an `io.ReadCloser`
* I also use csv.Reader which eliminates the need for the unfinished data handling
* I let the underlying transport handle buffering
This approach makes issues like #39 easier for fix, as only decorating the io.Reader with a ungzipper reader would be necessary.
Resolves #34
> Streaming query

- conn.go
This commit simplifies gzip compressed response handling.
Godoc clearly says that by default http.Transport will
add 'Accept-Encoding: gzip' to a Request and transparently
decode the response if a 'Content-Encoding: gzip' header
is present.
See https://golang.org/src/net/http/transport.go#L181
Therefore it is only necessary to add "enable_http_compression=1"
HTTP query parameter to Clickhouse server requests.
> Simplify compressed response handling

- stmt.go
- stmt_test.go
When insert query contains multiple lines batchmode is not working.
To fix that I have added regexp flag to match  "." to "\n"
> Fix for multiline insert queries

- conn.go
Issuing too many Exec()s leads to file descriptor exhaustion on Linux. This PR closes the response body in exec() before returning. Fixes #50 as @theoptz suggested.
> Close unused response bodies to avoid leaks.

- README.md
- conn.go
- conn_test.go
The PR adds support of `quota_key` and` query_id` for queries to Clickhouse for the driver.
Info about these Clickhouse settings could be found on official website - [quotas](https://clickhouse.yandex/docs/en/operations/quotas/) and [query_id](https://clickhouse.yandex/docs/en/interfaces/http/).
Keep in mind, that for reading info which `quota_key` or `query_id` was used for particular query, you should enable `log_queries` setting. Moreover, setting up `query_id` could potentially [replace executing query with the same id](https://clickhouse.yandex/docs/en/operations/settings/settings/#replace-running-query), which is depending on server settings.
I also added README.md instruction for supported params as well as tests. Feel free to send any comments and thoughts.
> Add support of setting query_id and quota_key for each query

- config.go
- conn.go
- tls_config.go
This PR adds support for custom TLS configuration, defined by the end user.
Based on the original implementation for: https://github.com/go-sql-driver/mysql
Fixes #41
/cc @bgaifullin
> Use custom TLS configuration #41

- README.md
- dataparser.go
- dataparser_test.go
When I select rows with LowCardinality field type without CAST I have an error: 
`type LowCardinality is not supported`
This is a fix.
> LowCardinality type dataparser support.

- conn_go18.go
- errors.go
When driver fails to connect to ClickHouse, the developers must
know the reason why it happened, this will dramatically help them
to solve the problem.
This commit reworks returned error for Ping method. Instead of
"bad connection", it will return the original error, when it occuirs.
Moreover, when the answer is not as expected (does not contain "Ok.")
the driver will explicitly return the message with the problem.
And for case when the transport is absent, developer will get explicit
message about it. There is no need to dive into the driver to catch
the responses to get to the bottom of the problem.
> Return original error when connection to ClickHouse failed

- conn.go
- conn_go18.go
Currently library generates big amount or errors on ClickHouse side:
<Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer
That's happens because of improper close of response body.
Documentation in net/http/response code states that to reuse keep-alive clients require to both read to competition and close body:
https://go.googlesource.com/go/+/go1.15.7/src/net/http/response.go#63
Unfortunately library only close response body without reading response body which leads to dropping keep-alive connections instead of reuse.
Also good discussion about this issue could be found here: https://github.com/google/go-github/pull/317
Tested on ClickHouse versions 19.16.12.49 and 20.8.12.2
> Drain response body on exec call to enable keep-alive connection reuse

- dataparser.go
- dataparser_test.go
I've noticed some time ago that Array(Nullable(TypeName)) elements can not be read from ClickHouse database properly.
So there's a solution for some data types.
P.S. + some tests of course
P.S.2. + fixed nil array element Parse() panic (dataparser.go:320)
dataparser.go: Array(Nullable(TypeName)) Parse() support where TypeName:
- UInt8-64
- Int8-64
- Float32-64
- String (also with escape seqs)
- Date (also with timezone)
- DateTime (also with timezone)
- Decimal
- Enum
- Uuid
- LowCardinality
> Support Array(Nullable(TypeName)) Parse() 

- README.md
- conn.go
- conn_go18.go
- conn_test.go
- go.mod
- go.sum
evolution of #115 
For using long SELECT's that are compatible to chproxy, we need to either put data in POST body or make a GET request with query parameter "query". 
As the request URL might be limited, we make all selects use POST requests.
> using POST requests and changing the uuid library to google

- conn.go
- conn_go18.go
- conn_go18_test.go
- rows.go
- stmt_go18_test.go
We have a few places where the library returns a raw error back to
the application. This is not a big problem if the error itself
provides enough information to identify the initial place/subsytem
where it occurred.
However, in this library some errors are confusing and it's unclear
where they happened and what actually they mean. As an example,
`driver: bad connection` or simply `EOF` were baffling me all the
time.
This commit makes errors more descriptive and keeps a possibility
to unwrap the initial error.
> Add more information about what the occurred error means

- dataparser.go
- dataparser_test.go
Per Clickhouse documentation, the SimpleAggregateFunction type can be treated as an opaque wrapper around the inner type.
> Support SimpleAggregateFunction types

- config.go
- config_test.go
This was not being configured in this method, even though `ParseDSN` supports it.
> Support configuring TLSConfig in FormatDSN

- README.md
If the read_timeout and write_timeout in the example do not add a unit, the "time: missing unit in duration" exception will occur. It is recommended to add it to the README file.
> Fix parameters's example in the README

- conn.go
- conn_go18_test.go
This feature will allow you to pass parameters to the service through the context. 
For example, it will be possible to control caching or labels in the request if you uses [chproxy](https://pkg.go.dev/github.com/richard403/chproxy#readme-caching)
> add settings_params pass from context for request to ClickHouse

- Makefile
New versions are located in clickhouse/clickhouse-server only.
> Change ClickHouse Docker repository.

- README.md
- clickhouse.go
- clickhouse_test.go
Exporting driver to enable sqltrace integration
> Export driver

- conn.go
We recently noticed that the clickhouse http interface can return Status 200 ok for failing queries. In particular when clickhouse runs into a socket read timeout for inserts, it will return a 200 but not write any data. In these cases it injects an error header, which remains unevaluated in the libs current implementation. Also it's not possible to evaluate the response client-side because the response is discarded here: https://github.com/mailru/go-clickhouse/blob/master/stmt.go#L111
In order not to change the libs interface we suggest to raise an error, if the error header is present in the connection request code
The underlying issue is the same as for https://github.com/mailru/go-clickhouse/pull/107/files (which was closed). But the fix then (wait_query_end=1) won't help in our case, …
> convert error header into request error
