mailru/go-clickhouse

- clickhouse_test.go
- conn.go
- conn_go18_test.go
- conn_test.go
- errors.go
- stmt.go
- stmt_test.go
stmt.Close may be called in same time as tx.Commit or tx.Rollback
this patch fixes it.
> Fix race in stmts

- conn_test.go
- encoder.go
- encoder_test.go
- helpers.go
- types.go
- types_test.go
> fix encoding date value

- clickhouse_test.go
- config_test.go
- conn_test.go
- encoder.go
- encoder_test.go
- helpers.go
- helpers_test.go
- interpolate_test.go
- rows_test.go
- stmt_test.go
- types_test.go
- sort imports (goimport)
- use var
- typo
> [FIX] Cleanup code

- conn.go
- conn_test.go
- errors.go
> Send readonly queries inside URL, not in the request body

- conn.go
- conn_test.go
- errors.go
This fix is related to issue https://github.com/mailru/go-clickhouse/issues/31
> Pass queries in readonly requests via body

- clickhouse_test.go
- config.go
- conn.go
- conn_test.go
This PR introduces gzip response compression. It's a Work-In-Progress, tests are missing. It's based off #38.
Resolves #39
> Add support for gzip compression

- helpers.go
buf should have the desired capacity but a length of zero
> fix capacity allocation

- dataparser.go
> Decimal support fixed

- dataparser.go
- dataparser_test.go
- rows.go
This PR fixes the FIXME comment on supporting custom locations on DateTime and Date fields
> Add DateTime default location and override options

- clickhouse_test.go
- config.go
- config_test.go
- conn.go
- conn_test.go
- go.mod
- go.sum
Add ability to automatically kill query in case of transport problem (timeout and etc.)
> add kill query option

- conn.go
- conn_test.go
> Fix parameters interpolation with empty params

- conn.go
- conn_test.go
Useful for massive data load to ClickHouse using simple INSERT INTO
On test environment data flow was dropped from 400MBit to 65Mbit using this patch
> Added support for gzip compression of request body

- conn.go
- conn_go18.go
- conn_test.go
- go.mod
chproxy on github:
https://github.com/Vertamedia/chproxy
1) Amending Ping logic: send version request with credentials due to chproxy is based on user  authentication 
2) Put sql query for CH for get requests into a request query due to chproxy expects sql query to be there for the get requests. Compatible with CH.
> making mailru driver compatible with chproxy

- Makefile
- stmt.go
> correct batch mode regex

- .travis.yml
- Makefile
- README.md
- conn.go
- conn_test.go
- dataparser.go
- encoder.go
- encoder_test.go
- tokenizer.go
- types.go
> tuple querying support

- dataparser.go
- dataparser_test.go
Add fix for nullable empty strings parsing
> Patch nullable empty strings parsing

- encoder.go
- encoder_test.go
- types.go
Implement Map clickhouse type.
> feat. impl map type

- dataparser.go
- dataparser_test.go
- helpers.go
Added implementation of DateTime64 that fixes issue #133
> implement DateTime64

- README.md
- clickhouse.go
- clickhouse_test.go
- go.mod
> change driver registration name to chhttp

- Makefile
- conn_go18_test.go
- conn_test.go
- typeparser.go
- fix unit tests
- upgrade golangci-lint version to 1.56.2 in Makefile
- fix ParseTypeDesc documentation
> fix(test): fix units tests

- conn.go
Don't use args from initial query in kill query
> fix killQuery if initial query has args
